# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)


Product.delete_all

Product.create(:category=>'картриджи', :producer=>'Brother', :model=>'TN-2075', :title=>'Brother TN-2075', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Brother HL-2030, 2040, 2070, DCP-7010, 7025, MFC-7420, 7820, FAX-2920', :capacity=>'приблизительно 2500 страниц при заполнении 5%', :weight=>0.848, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2327)
Product.create(:category=>'картриджи', :producer=>'Brother', :model=>'TN-2175', :title=>'Brother TN-2175', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Brother HL-2140R, 2142R, 2150NR, 2170WR, DCP-7030R, 7032R, 7045NR, MFC-7320R, 7440NR, 7840WR', :capacity=>'приблизительно 2600 страниц при заполнении 5%', :weight=>0.97, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2327)
Product.create(:category=>'картриджи', :producer=>'Brother', :model=>'TN-3060', :title=>'Brother TN-3060', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Brother HL5130, 5140, 5150D, 5170DN, MFC8440, 8840D, 8840DN, DCP8040', :capacity=>'приблизительно 6700страницпри заполнении 5%', :weight=>1.193, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>3627)
Product.create(:category=>'картриджи', :producer=>'Brother', :model=>'TN-3170', :title=>'Brother TN-3170', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Brother HL-5240, 5250DN, 5270DN', :capacity=>'приблизительно 7000страницпри заполнении 5%', :weight=>1.083, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>4407)
Product.create(:category=>'картриджи', :producer=>'Canon', :model=>'703', :title=>'Canon 703', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Canon i-SENSYSLBP2900, LBP2900B, LBP3000LaserShotLBP2900, LBP3000', :capacity=>'приблизительно 2000 страниц при заполнении 5%', :weight=>1, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2327)
Product.create(:category=>'картриджи', :producer=>'Canon', :model=>'712', :title=>'Canon 712', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'CanonLBP-3010, LBP-3100', :capacity=>'приблизительно 1500страницпри заполнении 5%', :weight=>0.8, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2665)
Product.create(:category=>'картриджи', :producer=>'Canon', :model=>'EP-22', :title=>'Canon EP-22', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Canon LaserShotLBP-1120, LBP-800, LBP-810', :capacity=>'приблизительно 2500 страниц при заполнении 5%', :weight=>1, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2067)
Product.create(:category=>'картриджи', :producer=>'Canon', :model=>'EP-25', :title=>'Canon EP-25', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Canon LaserShotLBP-1210', :capacity=>'приблизительно 2500 страниц при заполнении 5%', :weight=>1, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2327)
Product.create(:category=>'картриджи', :producer=>'Canon', :model=>'EP-27', :title=>'Canon EP-27', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Canon LaserBase MF5730, MF5750, MF5750, MF5770, MF5770, MF5730, MF5750, MF5770, i-SENSYSMF3228, LaserBaseMF3110, MF3240, MF5630, MF5650, MF5730, MF5750, MF5770', :capacity=>'приблизительно 2500 страниц при заполнении 5%', :weight=>0.6, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2327)
Product.create(:category=>'картриджи', :producer=>'Canon', :model=>'FX-10', :title=>'Canon FX-10', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Canon MF4120, MF4140, MF4150, MF4120, MF4140, MF4150, MF4320d, MF4330d, MF4340d, MF4350d, MF4370dn, MF4380dn, MF4018, MF4120, MF4140, MF4150, MF4270, MF4660PL, MF4690PL, FAX-L100, FAX-L120, FAX-L140, FAX-L160', :capacity=>'приблизительно 2000 страниц при заполнении 5%', :weight=>0.898, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2288)
Product.create(:category=>'картриджи', :producer=>'Canon', :model=>'FX-3', :title=>'Canon FX-3', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Canon FAX-L200, FAX-L220, FAX-L240, FAX-L250, FAX-L280, FAX-L290, FAX-L295, FAX-L300, FAX-L350, FAX-L360, MultiPASSL60, L90', :capacity=>'приблизительно 2700страницпри заполнении 5%', :weight=>1.056, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2418)
Product.create(:category=>'картриджи', :producer=>'Canon', :model=>'T', :title=>'Canon T', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Canon FAX-L400, PC-D320, PC-D340', :capacity=>'приблизительно 3500 страниц при заполнении 5%', :weight=>1.1, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>3887)
Product.create(:category=>'картриджи', :producer=>'Canon', :model=>'Е-16', :title=>'Canon Е-16', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Canon FC108, 120, 128, 200, 208, 210, 220, 224, 224s, 226, 228, 230, 330, 336, PC430, 780, 860, 890', :capacity=>'приблизительно 2000 страниц при заполнении 5%', :weight=>1.02, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2925)
Product.create(:category=>'картриджи', :producer=>'Canon', :model=>'Е-30', :title=>'Canon Е-30', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Canon FC100, 108, 120, 128, 200, 204, 206, 208, 210, 220, 224, 226, 228, 230, 310, 330, 336, 530, PC-740, 750, 760, 770, 780, 860, 880, 890', :capacity=>'приблизительно 4000страницпри заполнении 5%', :weight=>1.08, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>5967)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'C3906A', :title=>'HP C3906A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'НР LaserJet 5L/6/6L, 3100/3150', :capacity=>'2500 стандартных страниц при заполнении 5%', :weight=>0.97, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2197)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'C4092A', :title=>'HP C4092A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 1100и3200', :capacity=>'2500 стандартных страниц при заполнении 5%', :weight=>1, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2197)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'C4096A', :title=>'HP C4096A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 2100/2200', :capacity=>'5000 стандартных страниц при заполнении 5%', :weight=>1.65, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>3367)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'C4127A', :title=>'HP C4127A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 4000/4050', :capacity=>'6000 стандартных страниц при заполнении 5%', :weight=>1.8, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>3367)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'C4127X', :title=>'HP C4127X', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 4000/4050', :capacity=>'10000 стандартных страниц при заполнении 5%', :weight=>2, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>4927)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'C4129X', :title=>'HP C4129X', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 5000/5100', :capacity=>'10000 стандартных страниц при заполнении 5%', :weight=>2, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>6227)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'C4182X', :title=>'HP C4182X', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 8100/8150, Mopier320', :capacity=>'20000 стандартных страниц при заполнении 5%', :weight=>4.1, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>6487)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'C7115A', :title=>'HP C7115A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 1000w/1005w/1200/1220/3300', :capacity=>'2500 стандартных страниц при заполнении 5%', :weight=>1.03, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2158)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'C7115X', :title=>'HP C7115X', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 1200/1220/3300', :capacity=>'3500 стандартных страниц при заполнении 5%', :weight=>1.2, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2717)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'C8061A', :title=>'HP C8061A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 4100/mfp', :capacity=>'6000 стандартных страниц при заполнении 5%', :weight=>1.6, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>3757)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'C8061X', :title=>'HP C8061X', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 4100/mfp', :capacity=>'10000 стандартных страниц при заполнении 5%', :weight=>2, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>5187)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'C8543X', :title=>'HP C8543X', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet серий9000/mfp/9040/mfp/9050/mfp', :capacity=>'30000 стандартных страниц при заполнении 5%', :weight=>5.64, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>10387)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'CB435A', :title=>'HP CB435A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet P1005/P1006', :capacity=>'1500 стандартных страниц при заполнении 5%', :weight=>0.8, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2327)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'CB436A', :title=>'HP CB436A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 1505/1505n/1120/1120n/1522n/1522nf', :capacity=>'2000 стандартных страниц при заполнении 5%', :weight=>0.8, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2587)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'CB540A', :title=>'HP CB540A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP Color LaserJet CM1312, CM1312nfi, CP1215, CP1515n, CP1518ni', :capacity=>'2200 стандартных страниц при заполнении 5%', :weight=>0.8, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2847)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'CB541A', :title=>'HP CB541A', :print_tech=>'лазерная', :color=>'цветной', :compatibility=>'HP Color LaserJet CM1312, CM1312nfi, CP1215, CP1515n, CP1518ni', :capacity=>'1400 стандартных страниц при заполнении 5%', :weight=>0.8, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2704)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'CB542A', :title=>'HP CB542A', :print_tech=>'лазерная', :color=>'цветной', :compatibility=>'HP Color LaserJet CM1312, CM1312nfi, CP1215, CP1515n, CP1518ni', :capacity=>'1400 стандартных страниц при заполнении 5%', :weight=>0.8, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2704)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'CB543A', :title=>'HP CB543A', :print_tech=>'лазерная', :color=>'цветной', :compatibility=>'HP Color LaserJet CM1312, CM1312nfi, CP1215, CP1515n, CP1518ni', :capacity=>'1400 стандартных страниц при заполнении 5%', :weight=>0.8, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2704)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'CC364A', :title=>'HP CC364A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet P4014/P4015/P4515', :capacity=>'5000 стандартных страниц при заполнении 5%', :weight=>2.5, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>6357)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'CC364X', :title=>'HP CC364X', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet P4014/P4015/P4515', :capacity=>'24000 стандартных страниц при заполнении 5%', :weight=>3.34, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>10777)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'CE255A', :title=>'HP CE255A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 3010/3015', :capacity=>'6000 стандартных страниц при заполнении 5%', :weight=>1.82, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>5447)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'CE255Х', :title=>'HP CE255Х', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 3010/3015', :capacity=>'12500 стандартных страниц при заполнении 5%', :weight=>2.26, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>8567)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'CE505A', :title=>'HP CE505A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet P2055/P2035', :capacity=>'2300 стандартных страниц при заполнении 5%', :weight=>1, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>3107)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'CE505X', :title=>'HP CE505X', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet P2055/P2035', :capacity=>'6500 стандартных страниц при заполнении 5%', :weight=>1.3, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>5447)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'Q2610A', :title=>'HP Q2610A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet серии 2300', :capacity=>'6000 стандартных страниц при заполнении 5%', :weight=>1.6, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>3497)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'Q2612A', :title=>'HP Q2612A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 1010-12-15-18/1020-22/LJ3015-20-30/3050-52-55aio/M1005mfp', :capacity=>'2000 стандартных страниц при заполнении 5%', :weight=>0.9, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2469)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'Q2613A', :title=>'HP Q2613A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 1300', :capacity=>'2500 стандартных страниц при заполнении 5%', :weight=>1.07, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2535)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'Q2613X', :title=>'HP Q2613X', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet серии 1300', :capacity=>'4000 стандартных страниц при заполнении 5%', :weight=>1.14, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2925)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'Q2624A', :title=>'HP Q2624A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet серии 1150', :capacity=>'2500 стандартных страниц при заполнении 5%', :weight=>1.07, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2535)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'Q5942A', :title=>'HP Q5942A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet серий4250/4350', :capacity=>'10000 страниц при заполнении 5%', :weight=>2.8, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>5837)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'Q5942X', :title=>'HP Q5942X', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 4250/4350', :capacity=>'20000страницпри заполнении 5%', :weight=>3.2, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>8177)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'Q5949a', :title=>'HP Q5949a', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 1160/1320/3390aio/3392aio', :capacity=>'2500 стандартных страниц при заполнении 5%', :weight=>1, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2535)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'Q5949x', :title=>'HP Q5949x', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 1320/3390aio/3392aio', :capacity=>'6000 стандартных страниц при заполнении 5%', :weight=>1.3, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>4277)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'Q6000A', :title=>'HP Q6000A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP Color LaserJet 1600/2600/CM1015MFP', :capacity=>'2500 стандартных страниц при заполнении 5%', :weight=>1, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2925)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'Q6001A', :title=>'HP Q6001A', :print_tech=>'лазерная', :color=>'цветной', :compatibility=>'HP Color LaserJet 1600/2600/CM1015MFP', :capacity=>'2500 стандартных страниц при заполнении 5%', :weight=>1, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>3107)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'Q6002A', :title=>'HP Q6002A', :print_tech=>'лазерная', :color=>'цветной', :compatibility=>'HP Color LaserJet 1600/2600/CM1015MFP', :capacity=>'2000 стандартных страниц при заполнении 5%', :weight=>1, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>3107)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'Q6003A', :title=>'HP Q6003A', :print_tech=>'лазерная', :color=>'цветной', :compatibility=>'HP Color LaserJet 1600/2600/CM1015', :capacity=>'2000 стандартных страниц при заполнении 5%', :weight=>1, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>3107)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'Q6511A', :title=>'HP Q6511A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 2420/2430', :capacity=>'6000 стандартных страниц при заполнении 5%', :weight=>1.9, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>4277)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'Q6511X', :title=>'HP Q6511X', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 2420/2430', :capacity=>'12000 страниц при заполнении 5%', :weight=>2.3, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>7657)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'Q7516A', :title=>'HP Q7516A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP Color LaserJet 5200', :capacity=>'12000 страниц при заполнении 5%', :weight=>2.7, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>7787)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'Q7551A', :title=>'HP Q7551A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 3027, M3027, M3027X, 3035, M3035, M3035XS, 3005, P3005, P3005X, P3005D, P3005N, P3005DN', :capacity=>'6500 страниц при заполнении 5%', :weight=>1.9, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>4576)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'Q7551X', :title=>'HP Q7551X', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet 3027, M3027, M3027X, 3035, M3035, M3035XS, 3005, P3005, P3005X, P3005D, P3005N, P3005DN', :capacity=>'13000 страниц при заполнении 5%', :weight=>2.3, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>7787)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'Q7553A', :title=>'HP Q7553A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet2014/2015/2727', :capacity=>'3000стандартныхстраницпри заполнении 5%', :weight=>1, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2977)
Product.create(:category=>'картриджи', :producer=>'HP', :model=>'Q7553X', :title=>'HP Q7553X', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'HP LaserJet2014/2015/2727', :capacity=>'7000стандартныхстраницпри заполнении 5%', :weight=>1.3, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>5187)
Product.create(:category=>'картриджи', :producer=>'Kyocera', :model=>'TK-100', :title=>'Kyocera TK-100', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Kyocera KM-1500', :capacity=>'приблизительно 6000 страниц при заполнении 5%', :weight=>0.29, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2457)
Product.create(:category=>'картриджи', :producer=>'Kyocera', :model=>'TK-17', :title=>'Kyocera TK-17', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Kyocera MitaFS-1000, 1000+, 1010, 1050', :capacity=>'приблизительно 6000 страниц при заполнении 5%', :weight=>0.48, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2587)
Product.create(:category=>'картриджи', :producer=>'Kyocera', :model=>'TK-410', :title=>'Kyocera TK-410', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Kyocera KM-1620, KM-1635, KM-1650, KM-2020, KM-2035, KM-2050', :capacity=>'приблизительно 15000 страниц при заполнении 5%', :weight=>0.87, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>3237)
Product.create(:category=>'картриджи', :producer=>'Kyocera', :model=>'ТК-110', :title=>'Kyocera ТК-110', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Kyocera FS-720, FS-820, FS-920, FS-1016MFP, FS-1116MFP', :capacity=>'приблизительно 6000 страниц при заполнении 5%', :weight=>0.48, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>3705)
Product.create(:category=>'картриджи', :producer=>'Kyocera', :model=>'ТК-310', :title=>'Kyocera ТК-310', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Kyocera FS-2000D, FS-2000DN, 3900DN, 4000DN', :capacity=>'приблизительно 12000 страниц при заполнении 5%', :weight=>0.94, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>4537)
Product.create(:category=>'картриджи', :producer=>'Kyocera', :model=>'ТК-55', :title=>'Kyocera ТК-55', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Kyocera FS-1920', :capacity=>'приблизительно 15000 страниц при заполнении 5%', :weight=>1.07, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>4537)
Product.create(:category=>'картриджи', :producer=>'Panasonic', :model=>'KX-FA76A', :title=>'Panasonic KX-FA76A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Panasonic KX-FLM553RU, KX-FLB758RU, KX-FLB753RU, KX-FL503RU, KX-FL523RU', :capacity=>'приблизительно 2000 страниц при заполнении 5%', :weight=>0.3, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>897)
Product.create(:category=>'картриджи', :producer=>'Panasonic', :model=>'KX-FAT92A', :title=>'Panasonic KX-FAT92A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Panasonic KX-MB263RU, KX-MB283RU, KX-MB763RU, KX-MB773RU, KX-MB783RU', :capacity=>'приблизительно 2000 страниц при заполнении 5%', :weight=>0.153, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>1248)
Product.create(:category=>'картриджи', :producer=>'Panasonic', :model=>'KX-FA83A', :title=>'Panasonic KX-FA83A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Panasonic KX-FLM653RU, KX-FLM663RU, KX-FL513RU, KX-FL543RU', :capacity=>'приблизительно 2500 страниц при заполнении 5%', :weight=>0.295, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>1038.7)
Product.create(:category=>'картриджи', :producer=>'Panasonic', :model=>'KX-FA85A', :title=>'Panasonic KX-FA85A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Panasonic KX-FLB813RU, KX-FLB853RU, KX-FLB883RU', :capacity=>'приблизительно 5000 страниц при заполнении 5%', :weight=>0.603, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2457)
Product.create(:category=>'картриджи', :producer=>'Panasonic', :model=>'KX-FAT88A', :title=>'Panasonic KX-FAT88A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Panasonic KX-FL403RU, KX-FLC413RU', :capacity=>'приблизительно 2000 страниц при заполнении 5%', :weight=>0.327, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>1157)
Product.create(:category=>'картриджи', :producer=>'Samsung', :model=>'CLP-C300A', :title=>'Samsung CLP-C300A', :print_tech=>'лазерная', :color=>'цветной', :compatibility=>'Samsung CLP-300, 300N, CLX-2160, 2160N, 3160N, 3160FN', :capacity=>'1000 страниц при заполнении 5%', :weight=>0.25, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2067)
Product.create(:category=>'картриджи', :producer=>'Samsung', :model=>'CLP-K300A', :title=>'Samsung CLP-K300A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Samsung CLP-300, 300N, CLX-2160, 2160N, 3160N, 3160FN', :capacity=>'приблизительно 2000 страниц при заполнении 5%', :weight=>0.25, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2067)
Product.create(:category=>'картриджи', :producer=>'Samsung', :model=>'CLP-M300A', :title=>'Samsung CLP-M300A', :print_tech=>'лазерная', :color=>'цветной', :compatibility=>'Samsung CLP-300, 300N, CLX-2160, 2160N, 3160N, 3160FN', :capacity=>'приблизительно 1000 страниц при заполнении 5%', :weight=>0.11, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2067)
Product.create(:category=>'картриджи', :producer=>'Samsung', :model=>'CLP-Y300A', :title=>'Samsung CLP-Y300A', :print_tech=>'лазерная', :color=>'цветной', :compatibility=>'Samsung CLP-300, CLP-300N, CLX-2160, CLX-2160N, CLX-3160N, CLX-3160FN', :capacity=>'приблизительно 1000 страниц при заполнении 5%', :weight=>0.11, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2067)
Product.create(:category=>'картриджи', :producer=>'Samsung', :model=>'ML1210D3', :title=>'Samsung ML1210D3', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Samsung ML-1210, 1220M, 1250, 1430', :capacity=>'приблизительно 2500 страниц при заполнении 5%', :weight=>0.92, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2230)
Product.create(:category=>'картриджи', :producer=>'Samsung', :model=>'ML1520D3', :title=>'Samsung ML1520D3', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Samsung ML-1520', :capacity=>'приблизительно 3000 страниц при заполнении 5%', :weight=>1.1, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2444)
Product.create(:category=>'картриджи', :producer=>'Samsung', :model=>'ML1610D2', :title=>'Samsung ML1610D2', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Samsung ML-1610, 1615', :capacity=>'приблизительно 2000 страниц при заполнении 5%', :weight=>1.03, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2223)
Product.create(:category=>'картриджи', :producer=>'Samsung', :model=>'ML1710D3', :title=>'Samsung ML1710D3', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Samsung ML-1500, 1510, 1710, 1710P, 1740, 1750', :capacity=>'приблизительно 3000 страниц при заполнении 5%', :weight=>0.94, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2223)
Product.create(:category=>'картриджи', :producer=>'Samsung', :model=>'ML2010D3', :title=>'Samsung ML2010D3', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Samsung ML-2010, 2010P, 2015, 2510, 2570, 2571N', :capacity=>'приблизительно 3000 страниц при заполнении 5%', :weight=>1.24, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2275)
Product.create(:category=>'картриджи', :producer=>'Samsung', :model=>'MLD3050B', :title=>'Samsung MLD3050B', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Samsung ML-3050, ML-3051N, 3051ND', :capacity=>'приблизительно 8000 страниц при заполнении 5%', :weight=>2.05, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>5876)
Product.create(:category=>'картриджи', :producer=>'Samsung', :model=>'SCX-4100D3', :title=>'Samsung SCX-4100D3', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Samsung SCX-4100', :capacity=>'приблизительно 3000 страниц при заполнении 5%', :weight=>1.18, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2457)
Product.create(:category=>'картриджи', :producer=>'Samsung', :model=>'SCX4216D3', :title=>'Samsung SCX4216D3', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Samsung SF-560, 565P, SF-750, 755P, SCX-4016, 4116, 4216F', :capacity=>'приблизительно 3000 страниц при заполнении 5%', :weight=>1.14, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2587)
Product.create(:category=>'картриджи', :producer=>'Samsung', :model=>'SCX4521D3', :title=>'Samsung SCX4521D3', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Samsung SCX-4321, SCX-4521F', :capacity=>'приблизительно 3000 страниц при заполнении 5%', :weight=>1.39, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2379)
Product.create(:category=>'картриджи', :producer=>'Samsung', :model=>'SCX4720D3', :title=>'Samsung SCX4720D3', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Samsung SCX-4520, 4720F, 4720FN', :capacity=>'приблизительно 3000 страниц при заполнении 5%', :weight=>1.57, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2977)
Product.create(:category=>'картриджи', :producer=>'Samsung', :model=>'SCXD4200A', :title=>'Samsung SCXD4200A', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Samsung SCX-4220', :capacity=>'приблизительно 3000 страниц при заполнении 5%', :weight=>1.17, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2469)
Product.create(:category=>'картриджи', :producer=>'Xerox', :model=>'013R00606', :title=>'Xerox 013R00606', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Xerox WorkCentre PE120/PE120i', :capacity=>'приблизительно 5000 страниц при заполнении 5%', :weight=>1.282, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>4355)
Product.create(:category=>'картриджи', :producer=>'Xerox', :model=>'013R00607', :title=>'Xerox 013R00607', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Xerox WCPE114e', :capacity=>'приблизительно 3000 страниц при заполнении 5%', :weight=>1.102, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>3237)
Product.create(:category=>'картриджи', :producer=>'Xerox', :model=>'013R00621', :title=>'Xerox 013R00621', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Xerox WorkCentre PE220', :capacity=>'приблизительно 3000 страниц при заполнении 5%', :weight=>1.8, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>3757)
Product.create(:category=>'картриджи', :producer=>'Xerox', :model=>'013R00625', :title=>'Xerox 013R00625', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Xerox WorkCentre 3119', :capacity=>'приблизительно 3000 страниц при заполнении 5%', :weight=>1.064, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>3367)
Product.create(:category=>'картриджи', :producer=>'Xerox', :model=>'106R01159', :title=>'Xerox 106R01159', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Xerox Phaser3117, 3122, 3124, 3125', :capacity=>'приблизительно 3000 страниц при заполнении 5%', :weight=>1.045, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2847)
Product.create(:category=>'картриджи', :producer=>'Xerox', :model=>'106R01246', :title=>'Xerox 106R01246', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Xerox Phaser3428', :capacity=>'8000 стандартных страниц при заполнении 5%', :weight=>1.608, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>7397)
Product.create(:category=>'картриджи', :producer=>'Xerox', :model=>'109R00639', :title=>'Xerox 109R00639', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Xerox Phaser3110, 3210', :capacity=>'приблизительно 3000 страниц при заполнении 5%', :weight=>1.2, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2977)
Product.create(:category=>'картриджи', :producer=>'Xerox', :model=>'109R00725', :title=>'Xerox 109R00725', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Xerox Phaser3130, 3120, 3115, 3121', :capacity=>'приблизительно 3000 страниц при заполнении 5%', :weight=>1.064, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>2977)
Product.create(:category=>'картриджи', :producer=>'Xerox', :model=>'109R00746', :title=>'Xerox 109R00746', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Xerox Phaser3150', :capacity=>'приблизительно 3500 страниц при заполнении 5%', :weight=>1.36, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>3757)
Product.create(:category=>'картриджи', :producer=>'Xerox', :model=>'109R00747', :title=>'Xerox 109R00747', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Xerox Phaser3150', :capacity=>'приблизительно 5000 страниц при заполнении 5%', :weight=>1.18, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>4667)
Product.create(:category=>'картриджи', :producer=>'Xerox', :model=>'109R00748', :title=>'Xerox 109R00748', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Xerox Phaser3116', :capacity=>'приблизительно 3000 страниц при заполнении 5%', :weight=>0.9, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>3107)
Product.create(:category=>'картриджи', :producer=>'Xerox', :model=>'113R00296', :title=>'Xerox 113R00296', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Xerox P8E, P8ex, WorkCentre 385', :capacity=>'приблизительно 5000 страниц при заполнении 5%', :weight=>1.4, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>4537)
Product.create(:category=>'картриджи', :producer=>'Xerox', :model=>'113R00667', :title=>'Xerox 113R00667', :print_tech=>'лазерная', :color=>'черный', :compatibility=>'Xerox WorkCentrePE16, PE16, PE16e, 385', :capacity=>'приблизительно 3500 страниц при заполнении 5%', :weight=>1.021, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>4537)
Product.create(:category=>'термопленка', :producer=>'Panasonic', :model=>'KX-FA52A', :title=>'Panasonic KX-FA52A', :print_tech=>'термоперенос', :color=>'черный', :compatibility=>'Panasonic KX-FC228RU, KX-FC258RU, KX-FC278RU, KX-FP207RU, KX-FP218RU', :capacity=>'Длина 2х30м', :weight=>0.26, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>767)
Product.create(:category=>'термопленка', :producer=>'Panasonic', :model=>'KX-FA54A', :title=>'Panasonic KX-FA54A', :print_tech=>'термоперенос', :color=>'черный', :compatibility=>'Panasonic KX-FC233RU, KX-FC243RU, KX-FP143RU, KX-FP148RU', :capacity=>'Длина 2х35м', :weight=>0.26, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>767)
Product.create(:category=>'термопленка', :producer=>'Panasonic', :model=>'KX-FA55А', :title=>'Panasonic KX-FA55А', :print_tech=>'термоперенос', :color=>'черный', :compatibility=>'Panasonic KX-FC195RU, KX-FP153RU, KX-FP158RU, KX-FM90RU', :capacity=>'Длина 2х50м', :weight=>0.45, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>767)
Product.create(:category=>'термопленка', :producer=>'Panasonic', :model=>'KX-FA57A', :title=>'Panasonic KX-FA57A', :print_tech=>'термоперенос', :color=>'черный', :compatibility=>'Panasonic KX-FP343RU, KX-FP363RU, KX-FB423RU', :capacity=>'Длина 70м', :weight=>0.311, :description=>%{<p>описание товара на данный момент отсутствует</p>}, :price=>1027)
=begin
# . . .
Product.create(
:title => 'HP Q2612AProgramming Ruby 1.9_9',
:producer => 'HP',
:model => 'Q2612A',
:print_tech => 'Лазерный',
:color => 'Чёрный',
:compatibility => 'HP LaserJet 1010-12-15-18/1020-22/LJ 3015-20-30/3050-52-55aio/M1005mfp',
:capacity => '2000 стандартных страниц при заполнении 5%',
:weight => 0.9,
:description =>%{<p>
картриджи семейства Q2612 для принтеров HP LaserJet с тонером Ultraprecise обеспечивают повышенную чёткость чёрного текста и плавность переходов оттенков серого цвета и полутонов. Геликоидальный приводной механизм устраняет полосатость, гарантируя неизменную точность, качество, надёжность высокопроизводительной печати.
Чёткое взаимодействие компонентов служит гарантией неизменно надёжной работы картриджей семейства Q2612 для принтеров HP LaserJet, а конструктивно присущая им надёжность, наряду со строжайшим контролем качества, гарантирует безотказную работу принтера при минимальном участии пользователя.
Удобная, функционально законченная конструкция картриджей семейства Q2612 для принтеров HP LaserJet с тонером Ultraprecise обеспечивает их установку и обслуживание без усилий. Магнитные уплотнения надёжно запирают тонер в картридже, предотвращая его утечку.
</p>},
:price => 2500)
# . . .
=end
